application: blog-gordon
runtime: python27
api_version: 1
threadsafe: no
version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js
  expiration: " 0d 1h"

- url: /login
  script: admin.app

- url: /admin/.*
  script: admin.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: 2.6